//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaseFilter.FolderLocker.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name accountName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignInAccount", ReplyAction="*")]
        EaseFilter.FolderLocker.ServiceReference1.SignInAccountResponse SignInAccount(EaseFilter.FolderLocker.ServiceReference1.SignInAccountRequest request);
        
        // CODEGEN: Generating message contract since element name accountName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignUpAccount", ReplyAction="*")]
        EaseFilter.FolderLocker.ServiceReference1.SignUpAccountResponse SignUpAccount(EaseFilter.FolderLocker.ServiceReference1.SignUpAccountRequest request);
        
        // CODEGEN: Generating message contract since element name accountName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileList", ReplyAction="*")]
        EaseFilter.FolderLocker.ServiceReference1.GetFileListResponse GetFileList(EaseFilter.FolderLocker.ServiceReference1.GetFileListRequest request);
        
        // CODEGEN: Generating message contract since element name accountName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddShareFile", ReplyAction="*")]
        EaseFilter.FolderLocker.ServiceReference1.AddShareFileResponse AddShareFile(EaseFilter.FolderLocker.ServiceReference1.AddShareFileRequest request);
        
        // CODEGEN: Generating message contract since element name accountName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSharedFile", ReplyAction="*")]
        EaseFilter.FolderLocker.ServiceReference1.DeleteSharedFileResponse DeleteSharedFile(EaseFilter.FolderLocker.ServiceReference1.DeleteSharedFileRequest request);
        
        // CODEGEN: Generating message contract since element name accountName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSharedFileDRInfo", ReplyAction="*")]
        EaseFilter.FolderLocker.ServiceReference1.GetSharedFileDRInfoResponse GetSharedFileDRInfo(EaseFilter.FolderLocker.ServiceReference1.GetSharedFileDRInfoRequest request);
        
        // CODEGEN: Generating message contract since element name accountName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifySharedFileDRInfo", ReplyAction="*")]
        EaseFilter.FolderLocker.ServiceReference1.ModifySharedFileDRInfoResponse ModifySharedFileDRInfo(EaseFilter.FolderLocker.ServiceReference1.ModifySharedFileDRInfoRequest request);
        
        // CODEGEN: Generating message contract since element name accountName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccessLog", ReplyAction="*")]
        EaseFilter.FolderLocker.ServiceReference1.GetAccessLogResponse GetAccessLog(EaseFilter.FolderLocker.ServiceReference1.GetAccessLogRequest request);
        
        // CODEGEN: Generating message contract since element name accountName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClearAccessLog", ReplyAction="*")]
        EaseFilter.FolderLocker.ServiceReference1.ClearAccessLogResponse ClearAccessLog(EaseFilter.FolderLocker.ServiceReference1.ClearAccessLogRequest request);
        
        // CODEGEN: Generating message contract since element name userInfoStr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSharedFilePermission", ReplyAction="*")]
        EaseFilter.FolderLocker.ServiceReference1.GetSharedFilePermissionResponse GetSharedFilePermission(EaseFilter.FolderLocker.ServiceReference1.GetSharedFilePermissionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignInAccount", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.SignInAccountRequestBody Body;
        
        public SignInAccountRequest() {
        }
        
        public SignInAccountRequest(EaseFilter.FolderLocker.ServiceReference1.SignInAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastError;
        
        public SignInAccountRequestBody() {
        }
        
        public SignInAccountRequestBody(string accountName, string password, string lastError) {
            this.accountName = accountName;
            this.password = password;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignInAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.SignInAccountResponseBody Body;
        
        public SignInAccountResponse() {
        }
        
        public SignInAccountResponse(EaseFilter.FolderLocker.ServiceReference1.SignInAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SignInAccountResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastError;
        
        public SignInAccountResponseBody() {
        }
        
        public SignInAccountResponseBody(bool SignInAccountResult, string lastError) {
            this.SignInAccountResult = SignInAccountResult;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignUpAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignUpAccount", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.SignUpAccountRequestBody Body;
        
        public SignUpAccountRequest() {
        }
        
        public SignUpAccountRequest(EaseFilter.FolderLocker.ServiceReference1.SignUpAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignUpAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastError;
        
        public SignUpAccountRequestBody() {
        }
        
        public SignUpAccountRequestBody(string accountName, string password, string lastError) {
            this.accountName = accountName;
            this.password = password;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignUpAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignUpAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.SignUpAccountResponseBody Body;
        
        public SignUpAccountResponse() {
        }
        
        public SignUpAccountResponse(EaseFilter.FolderLocker.ServiceReference1.SignUpAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignUpAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SignUpAccountResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastError;
        
        public SignUpAccountResponseBody() {
        }
        
        public SignUpAccountResponseBody(bool SignUpAccountResult, string lastError) {
            this.SignUpAccountResult = SignUpAccountResult;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileList", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.GetFileListRequestBody Body;
        
        public GetFileListRequest() {
        }
        
        public GetFileListRequest(EaseFilter.FolderLocker.ServiceReference1.GetFileListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string lastError;
        
        public GetFileListRequestBody() {
        }
        
        public GetFileListRequestBody(string accountName, string password, string fileList, string lastError) {
            this.accountName = accountName;
            this.password = password;
            this.fileList = fileList;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileListResponse", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.GetFileListResponseBody Body;
        
        public GetFileListResponse() {
        }
        
        public GetFileListResponse(EaseFilter.FolderLocker.ServiceReference1.GetFileListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetFileListResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastError;
        
        public GetFileListResponseBody() {
        }
        
        public GetFileListResponseBody(bool GetFileListResult, string fileList, string lastError) {
            this.GetFileListResult = GetFileListResult;
            this.fileList = fileList;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddShareFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddShareFile", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.AddShareFileRequestBody Body;
        
        public AddShareFileRequest() {
        }
        
        public AddShareFileRequest(EaseFilter.FolderLocker.ServiceReference1.AddShareFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddShareFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string policy;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long creationTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string iv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string lastError;
        
        public AddShareFileRequestBody() {
        }
        
        public AddShareFileRequestBody(string accountName, string password, string policy, long creationTime, string key, string iv, string lastError) {
            this.accountName = accountName;
            this.password = password;
            this.policy = policy;
            this.creationTime = creationTime;
            this.key = key;
            this.iv = iv;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddShareFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddShareFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.AddShareFileResponseBody Body;
        
        public AddShareFileResponse() {
        }
        
        public AddShareFileResponse(EaseFilter.FolderLocker.ServiceReference1.AddShareFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddShareFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddShareFileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long creationTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string iv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string lastError;
        
        public AddShareFileResponseBody() {
        }
        
        public AddShareFileResponseBody(bool AddShareFileResult, long creationTime, string key, string iv, string lastError) {
            this.AddShareFileResult = AddShareFileResult;
            this.creationTime = creationTime;
            this.key = key;
            this.iv = iv;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSharedFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSharedFile", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.DeleteSharedFileRequestBody Body;
        
        public DeleteSharedFileRequest() {
        }
        
        public DeleteSharedFileRequest(EaseFilter.FolderLocker.ServiceReference1.DeleteSharedFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSharedFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string encryptionIV;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string lastError;
        
        public DeleteSharedFileRequestBody() {
        }
        
        public DeleteSharedFileRequestBody(string accountName, string password, string encryptionIV, string lastError) {
            this.accountName = accountName;
            this.password = password;
            this.encryptionIV = encryptionIV;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSharedFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSharedFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.DeleteSharedFileResponseBody Body;
        
        public DeleteSharedFileResponse() {
        }
        
        public DeleteSharedFileResponse(EaseFilter.FolderLocker.ServiceReference1.DeleteSharedFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSharedFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteSharedFileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastError;
        
        public DeleteSharedFileResponseBody() {
        }
        
        public DeleteSharedFileResponseBody(bool DeleteSharedFileResult, string lastError) {
            this.DeleteSharedFileResult = DeleteSharedFileResult;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSharedFileDRInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSharedFileDRInfo", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.GetSharedFileDRInfoRequestBody Body;
        
        public GetSharedFileDRInfoRequest() {
        }
        
        public GetSharedFileDRInfoRequest(EaseFilter.FolderLocker.ServiceReference1.GetSharedFileDRInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSharedFileDRInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ivStr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string encryptedDRPolicy;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string lastError;
        
        public GetSharedFileDRInfoRequestBody() {
        }
        
        public GetSharedFileDRInfoRequestBody(string accountName, string password, string ivStr, string encryptedDRPolicy, string lastError) {
            this.accountName = accountName;
            this.password = password;
            this.ivStr = ivStr;
            this.encryptedDRPolicy = encryptedDRPolicy;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSharedFileDRInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSharedFileDRInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.GetSharedFileDRInfoResponseBody Body;
        
        public GetSharedFileDRInfoResponse() {
        }
        
        public GetSharedFileDRInfoResponse(EaseFilter.FolderLocker.ServiceReference1.GetSharedFileDRInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSharedFileDRInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetSharedFileDRInfoResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encryptedDRPolicy;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastError;
        
        public GetSharedFileDRInfoResponseBody() {
        }
        
        public GetSharedFileDRInfoResponseBody(bool GetSharedFileDRInfoResult, string encryptedDRPolicy, string lastError) {
            this.GetSharedFileDRInfoResult = GetSharedFileDRInfoResult;
            this.encryptedDRPolicy = encryptedDRPolicy;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifySharedFileDRInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifySharedFileDRInfo", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.ModifySharedFileDRInfoRequestBody Body;
        
        public ModifySharedFileDRInfoRequest() {
        }
        
        public ModifySharedFileDRInfoRequest(EaseFilter.FolderLocker.ServiceReference1.ModifySharedFileDRInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifySharedFileDRInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string encryptedDRPolicy;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string lastError;
        
        public ModifySharedFileDRInfoRequestBody() {
        }
        
        public ModifySharedFileDRInfoRequestBody(string accountName, string password, string encryptedDRPolicy, string lastError) {
            this.accountName = accountName;
            this.password = password;
            this.encryptedDRPolicy = encryptedDRPolicy;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifySharedFileDRInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifySharedFileDRInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.ModifySharedFileDRInfoResponseBody Body;
        
        public ModifySharedFileDRInfoResponse() {
        }
        
        public ModifySharedFileDRInfoResponse(EaseFilter.FolderLocker.ServiceReference1.ModifySharedFileDRInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifySharedFileDRInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ModifySharedFileDRInfoResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastError;
        
        public ModifySharedFileDRInfoResponseBody() {
        }
        
        public ModifySharedFileDRInfoResponseBody(bool ModifySharedFileDRInfoResult, string lastError) {
            this.ModifySharedFileDRInfoResult = ModifySharedFileDRInfoResult;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessLog", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.GetAccessLogRequestBody Body;
        
        public GetAccessLogRequest() {
        }
        
        public GetAccessLogRequest(EaseFilter.FolderLocker.ServiceReference1.GetAccessLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccessLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string accessLog;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string lastError;
        
        public GetAccessLogRequestBody() {
        }
        
        public GetAccessLogRequestBody(string accountName, string password, string accessLog, string lastError) {
            this.accountName = accountName;
            this.password = password;
            this.accessLog = accessLog;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.GetAccessLogResponseBody Body;
        
        public GetAccessLogResponse() {
        }
        
        public GetAccessLogResponse(EaseFilter.FolderLocker.ServiceReference1.GetAccessLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccessLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetAccessLogResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accessLog;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastError;
        
        public GetAccessLogResponseBody() {
        }
        
        public GetAccessLogResponseBody(bool GetAccessLogResult, string accessLog, string lastError) {
            this.GetAccessLogResult = GetAccessLogResult;
            this.accessLog = accessLog;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClearAccessLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClearAccessLog", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.ClearAccessLogRequestBody Body;
        
        public ClearAccessLogRequest() {
        }
        
        public ClearAccessLogRequest(EaseFilter.FolderLocker.ServiceReference1.ClearAccessLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClearAccessLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastError;
        
        public ClearAccessLogRequestBody() {
        }
        
        public ClearAccessLogRequestBody(string accountName, string password, string lastError) {
            this.accountName = accountName;
            this.password = password;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClearAccessLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClearAccessLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.ClearAccessLogResponseBody Body;
        
        public ClearAccessLogResponse() {
        }
        
        public ClearAccessLogResponse(EaseFilter.FolderLocker.ServiceReference1.ClearAccessLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClearAccessLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ClearAccessLogResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastError;
        
        public ClearAccessLogResponseBody() {
        }
        
        public ClearAccessLogResponseBody(bool ClearAccessLogResult, string lastError) {
            this.ClearAccessLogResult = ClearAccessLogResult;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSharedFilePermissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSharedFilePermission", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.GetSharedFilePermissionRequestBody Body;
        
        public GetSharedFilePermissionRequest() {
        }
        
        public GetSharedFilePermissionRequest(EaseFilter.FolderLocker.ServiceReference1.GetSharedFilePermissionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSharedFilePermissionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userInfoStr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string iv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public uint accessFlags;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string lastError;
        
        public GetSharedFilePermissionRequestBody() {
        }
        
        public GetSharedFilePermissionRequestBody(string userInfoStr, string key, string iv, uint accessFlags, string lastError) {
            this.userInfoStr = userInfoStr;
            this.key = key;
            this.iv = iv;
            this.accessFlags = accessFlags;
            this.lastError = lastError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSharedFilePermissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSharedFilePermissionResponse", Namespace="http://tempuri.org/", Order=0)]
        public EaseFilter.FolderLocker.ServiceReference1.GetSharedFilePermissionResponseBody Body;
        
        public GetSharedFilePermissionResponse() {
        }
        
        public GetSharedFilePermissionResponse(EaseFilter.FolderLocker.ServiceReference1.GetSharedFilePermissionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSharedFilePermissionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetSharedFilePermissionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string iv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public uint accessFlags;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string lastError;
        
        public GetSharedFilePermissionResponseBody() {
        }
        
        public GetSharedFilePermissionResponseBody(bool GetSharedFilePermissionResult, string key, string iv, uint accessFlags, string lastError) {
            this.GetSharedFilePermissionResult = GetSharedFilePermissionResult;
            this.key = key;
            this.iv = iv;
            this.accessFlags = accessFlags;
            this.lastError = lastError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : EaseFilter.FolderLocker.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<EaseFilter.FolderLocker.ServiceReference1.ServiceSoap>, EaseFilter.FolderLocker.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaseFilter.FolderLocker.ServiceReference1.SignInAccountResponse EaseFilter.FolderLocker.ServiceReference1.ServiceSoap.SignInAccount(EaseFilter.FolderLocker.ServiceReference1.SignInAccountRequest request) {
            return base.Channel.SignInAccount(request);
        }
        
        public bool SignInAccount(string accountName, string password, ref string lastError) {
            EaseFilter.FolderLocker.ServiceReference1.SignInAccountRequest inValue = new EaseFilter.FolderLocker.ServiceReference1.SignInAccountRequest();
            inValue.Body = new EaseFilter.FolderLocker.ServiceReference1.SignInAccountRequestBody();
            inValue.Body.accountName = accountName;
            inValue.Body.password = password;
            inValue.Body.lastError = lastError;
            EaseFilter.FolderLocker.ServiceReference1.SignInAccountResponse retVal = ((EaseFilter.FolderLocker.ServiceReference1.ServiceSoap)(this)).SignInAccount(inValue);
            lastError = retVal.Body.lastError;
            return retVal.Body.SignInAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaseFilter.FolderLocker.ServiceReference1.SignUpAccountResponse EaseFilter.FolderLocker.ServiceReference1.ServiceSoap.SignUpAccount(EaseFilter.FolderLocker.ServiceReference1.SignUpAccountRequest request) {
            return base.Channel.SignUpAccount(request);
        }
        
        public bool SignUpAccount(string accountName, string password, ref string lastError) {
            EaseFilter.FolderLocker.ServiceReference1.SignUpAccountRequest inValue = new EaseFilter.FolderLocker.ServiceReference1.SignUpAccountRequest();
            inValue.Body = new EaseFilter.FolderLocker.ServiceReference1.SignUpAccountRequestBody();
            inValue.Body.accountName = accountName;
            inValue.Body.password = password;
            inValue.Body.lastError = lastError;
            EaseFilter.FolderLocker.ServiceReference1.SignUpAccountResponse retVal = ((EaseFilter.FolderLocker.ServiceReference1.ServiceSoap)(this)).SignUpAccount(inValue);
            lastError = retVal.Body.lastError;
            return retVal.Body.SignUpAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaseFilter.FolderLocker.ServiceReference1.GetFileListResponse EaseFilter.FolderLocker.ServiceReference1.ServiceSoap.GetFileList(EaseFilter.FolderLocker.ServiceReference1.GetFileListRequest request) {
            return base.Channel.GetFileList(request);
        }
        
        public bool GetFileList(string accountName, string password, ref string fileList, ref string lastError) {
            EaseFilter.FolderLocker.ServiceReference1.GetFileListRequest inValue = new EaseFilter.FolderLocker.ServiceReference1.GetFileListRequest();
            inValue.Body = new EaseFilter.FolderLocker.ServiceReference1.GetFileListRequestBody();
            inValue.Body.accountName = accountName;
            inValue.Body.password = password;
            inValue.Body.fileList = fileList;
            inValue.Body.lastError = lastError;
            EaseFilter.FolderLocker.ServiceReference1.GetFileListResponse retVal = ((EaseFilter.FolderLocker.ServiceReference1.ServiceSoap)(this)).GetFileList(inValue);
            fileList = retVal.Body.fileList;
            lastError = retVal.Body.lastError;
            return retVal.Body.GetFileListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaseFilter.FolderLocker.ServiceReference1.AddShareFileResponse EaseFilter.FolderLocker.ServiceReference1.ServiceSoap.AddShareFile(EaseFilter.FolderLocker.ServiceReference1.AddShareFileRequest request) {
            return base.Channel.AddShareFile(request);
        }
        
        public bool AddShareFile(string accountName, string password, string policy, ref long creationTime, ref string key, ref string iv, ref string lastError) {
            EaseFilter.FolderLocker.ServiceReference1.AddShareFileRequest inValue = new EaseFilter.FolderLocker.ServiceReference1.AddShareFileRequest();
            inValue.Body = new EaseFilter.FolderLocker.ServiceReference1.AddShareFileRequestBody();
            inValue.Body.accountName = accountName;
            inValue.Body.password = password;
            inValue.Body.policy = policy;
            inValue.Body.creationTime = creationTime;
            inValue.Body.key = key;
            inValue.Body.iv = iv;
            inValue.Body.lastError = lastError;
            EaseFilter.FolderLocker.ServiceReference1.AddShareFileResponse retVal = ((EaseFilter.FolderLocker.ServiceReference1.ServiceSoap)(this)).AddShareFile(inValue);
            creationTime = retVal.Body.creationTime;
            key = retVal.Body.key;
            iv = retVal.Body.iv;
            lastError = retVal.Body.lastError;
            return retVal.Body.AddShareFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaseFilter.FolderLocker.ServiceReference1.DeleteSharedFileResponse EaseFilter.FolderLocker.ServiceReference1.ServiceSoap.DeleteSharedFile(EaseFilter.FolderLocker.ServiceReference1.DeleteSharedFileRequest request) {
            return base.Channel.DeleteSharedFile(request);
        }
        
        public bool DeleteSharedFile(string accountName, string password, string encryptionIV, ref string lastError) {
            EaseFilter.FolderLocker.ServiceReference1.DeleteSharedFileRequest inValue = new EaseFilter.FolderLocker.ServiceReference1.DeleteSharedFileRequest();
            inValue.Body = new EaseFilter.FolderLocker.ServiceReference1.DeleteSharedFileRequestBody();
            inValue.Body.accountName = accountName;
            inValue.Body.password = password;
            inValue.Body.encryptionIV = encryptionIV;
            inValue.Body.lastError = lastError;
            EaseFilter.FolderLocker.ServiceReference1.DeleteSharedFileResponse retVal = ((EaseFilter.FolderLocker.ServiceReference1.ServiceSoap)(this)).DeleteSharedFile(inValue);
            lastError = retVal.Body.lastError;
            return retVal.Body.DeleteSharedFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaseFilter.FolderLocker.ServiceReference1.GetSharedFileDRInfoResponse EaseFilter.FolderLocker.ServiceReference1.ServiceSoap.GetSharedFileDRInfo(EaseFilter.FolderLocker.ServiceReference1.GetSharedFileDRInfoRequest request) {
            return base.Channel.GetSharedFileDRInfo(request);
        }
        
        public bool GetSharedFileDRInfo(string accountName, string password, string ivStr, ref string encryptedDRPolicy, ref string lastError) {
            EaseFilter.FolderLocker.ServiceReference1.GetSharedFileDRInfoRequest inValue = new EaseFilter.FolderLocker.ServiceReference1.GetSharedFileDRInfoRequest();
            inValue.Body = new EaseFilter.FolderLocker.ServiceReference1.GetSharedFileDRInfoRequestBody();
            inValue.Body.accountName = accountName;
            inValue.Body.password = password;
            inValue.Body.ivStr = ivStr;
            inValue.Body.encryptedDRPolicy = encryptedDRPolicy;
            inValue.Body.lastError = lastError;
            EaseFilter.FolderLocker.ServiceReference1.GetSharedFileDRInfoResponse retVal = ((EaseFilter.FolderLocker.ServiceReference1.ServiceSoap)(this)).GetSharedFileDRInfo(inValue);
            encryptedDRPolicy = retVal.Body.encryptedDRPolicy;
            lastError = retVal.Body.lastError;
            return retVal.Body.GetSharedFileDRInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaseFilter.FolderLocker.ServiceReference1.ModifySharedFileDRInfoResponse EaseFilter.FolderLocker.ServiceReference1.ServiceSoap.ModifySharedFileDRInfo(EaseFilter.FolderLocker.ServiceReference1.ModifySharedFileDRInfoRequest request) {
            return base.Channel.ModifySharedFileDRInfo(request);
        }
        
        public bool ModifySharedFileDRInfo(string accountName, string password, string encryptedDRPolicy, ref string lastError) {
            EaseFilter.FolderLocker.ServiceReference1.ModifySharedFileDRInfoRequest inValue = new EaseFilter.FolderLocker.ServiceReference1.ModifySharedFileDRInfoRequest();
            inValue.Body = new EaseFilter.FolderLocker.ServiceReference1.ModifySharedFileDRInfoRequestBody();
            inValue.Body.accountName = accountName;
            inValue.Body.password = password;
            inValue.Body.encryptedDRPolicy = encryptedDRPolicy;
            inValue.Body.lastError = lastError;
            EaseFilter.FolderLocker.ServiceReference1.ModifySharedFileDRInfoResponse retVal = ((EaseFilter.FolderLocker.ServiceReference1.ServiceSoap)(this)).ModifySharedFileDRInfo(inValue);
            lastError = retVal.Body.lastError;
            return retVal.Body.ModifySharedFileDRInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaseFilter.FolderLocker.ServiceReference1.GetAccessLogResponse EaseFilter.FolderLocker.ServiceReference1.ServiceSoap.GetAccessLog(EaseFilter.FolderLocker.ServiceReference1.GetAccessLogRequest request) {
            return base.Channel.GetAccessLog(request);
        }
        
        public bool GetAccessLog(string accountName, string password, ref string accessLog, ref string lastError) {
            EaseFilter.FolderLocker.ServiceReference1.GetAccessLogRequest inValue = new EaseFilter.FolderLocker.ServiceReference1.GetAccessLogRequest();
            inValue.Body = new EaseFilter.FolderLocker.ServiceReference1.GetAccessLogRequestBody();
            inValue.Body.accountName = accountName;
            inValue.Body.password = password;
            inValue.Body.accessLog = accessLog;
            inValue.Body.lastError = lastError;
            EaseFilter.FolderLocker.ServiceReference1.GetAccessLogResponse retVal = ((EaseFilter.FolderLocker.ServiceReference1.ServiceSoap)(this)).GetAccessLog(inValue);
            accessLog = retVal.Body.accessLog;
            lastError = retVal.Body.lastError;
            return retVal.Body.GetAccessLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaseFilter.FolderLocker.ServiceReference1.ClearAccessLogResponse EaseFilter.FolderLocker.ServiceReference1.ServiceSoap.ClearAccessLog(EaseFilter.FolderLocker.ServiceReference1.ClearAccessLogRequest request) {
            return base.Channel.ClearAccessLog(request);
        }
        
        public bool ClearAccessLog(string accountName, string password, ref string lastError) {
            EaseFilter.FolderLocker.ServiceReference1.ClearAccessLogRequest inValue = new EaseFilter.FolderLocker.ServiceReference1.ClearAccessLogRequest();
            inValue.Body = new EaseFilter.FolderLocker.ServiceReference1.ClearAccessLogRequestBody();
            inValue.Body.accountName = accountName;
            inValue.Body.password = password;
            inValue.Body.lastError = lastError;
            EaseFilter.FolderLocker.ServiceReference1.ClearAccessLogResponse retVal = ((EaseFilter.FolderLocker.ServiceReference1.ServiceSoap)(this)).ClearAccessLog(inValue);
            lastError = retVal.Body.lastError;
            return retVal.Body.ClearAccessLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EaseFilter.FolderLocker.ServiceReference1.GetSharedFilePermissionResponse EaseFilter.FolderLocker.ServiceReference1.ServiceSoap.GetSharedFilePermission(EaseFilter.FolderLocker.ServiceReference1.GetSharedFilePermissionRequest request) {
            return base.Channel.GetSharedFilePermission(request);
        }
        
        public bool GetSharedFilePermission(string userInfoStr, ref string key, ref string iv, ref uint accessFlags, ref string lastError) {
            EaseFilter.FolderLocker.ServiceReference1.GetSharedFilePermissionRequest inValue = new EaseFilter.FolderLocker.ServiceReference1.GetSharedFilePermissionRequest();
            inValue.Body = new EaseFilter.FolderLocker.ServiceReference1.GetSharedFilePermissionRequestBody();
            inValue.Body.userInfoStr = userInfoStr;
            inValue.Body.key = key;
            inValue.Body.iv = iv;
            inValue.Body.accessFlags = accessFlags;
            inValue.Body.lastError = lastError;
            EaseFilter.FolderLocker.ServiceReference1.GetSharedFilePermissionResponse retVal = ((EaseFilter.FolderLocker.ServiceReference1.ServiceSoap)(this)).GetSharedFilePermission(inValue);
            key = retVal.Body.key;
            iv = retVal.Body.iv;
            accessFlags = retVal.Body.accessFlags;
            lastError = retVal.Body.lastError;
            return retVal.Body.GetSharedFilePermissionResult;
        }
    }
}
